# Generated by Django 2.2.3 on 2019-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_application_hosttoapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='app01.HOST'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
