# Generated by Django 2.2.3 on 2019-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.URLField(max_length=19, null=True),
        ),
    ]
