# Generated by Django 2.2.3 on 2019-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_userinfo_user_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, 'VIP用户')], db_column='user_type', default=1),
        ),
    ]
