# Generated by Django 2.2.3 on 2019-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20190829_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='test',
            field=models.URLField(blank=True, max_length=19, null=True),
        ),
    ]
